[project]
name = "auto-diff"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "jax>=0.8.1",
    "numpy>=2.3.5",
    "rich>=14.2.0",
    "scikit-learn>=1.8.0",
    "sympy>=1.14.0",
]
